export const API_ROUTES = {
  AUTH: {
    REGISTER: '/api/auth/register',
    LOGIN: '/api/auth/login',
    RESET_REQUEST: '/api/auth/reset-request',
    RESET_PASSWORD: '/api/auth/reset-password',
    PROFILE: '/api/users/profile',
  },
  ORGANIZATIONS: {
    LIST: '/api/organizations',
    REGISTER: '/api/organizations/register',
    LOGIN: '/api/organizations/login',
USERS: '/api/organizations/users',
    APPROVE_USER: function(id) { return '/api/organizations/users/' + id + '/approve'; },
    REJECT_USER: function(id) { return '/api/organizations/users/' + id + '/reject'; },
    GROUPS: '/api/organizations/groups',
    CREATE_GROUP: '/api/organizations/groups/create',
    UPDATE_GROUP: function(id) { return '/api/organizations/groups/' + id; },
    DELETE_GROUP: function(id) { return '/api/organizations/groups/' + id; },
    FILES: '/api/organizations/files',
  },
  USERS: {
    PROFILE: '/api/users/profile',
    UPDATE_PROFILE: '/api/users/update-profile',
    AVATAR: '/api/users/avatar',
  },
  FILES: {
    UPLOAD: '/api/files/upload',
    LIST: '/api/files',
    DELETE: '/api/files/delete',
    BY_GROUP: function(groupId) { return '/api/files/' + groupId; },
  },
  GROUPS: {
    LIST: '/api/groups',
    CREATE: '/api/groups/create',
    JOIN: '/api/groups/join',
    LEAVE: '/api/groups/leave',
    MESSAGES: function(groupId) { return '/api/groups/' + groupId + '/messages'; },
    AGORA_TOKEN: function(groupId) { return '/api/groups/' + groupId + '/agora-token'; },
  },
};